modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/CMSC-389E/mod-and-testing-framework/issues"

[[mods]]
modId="circuitry"
version="${file.jarVersion}"
displayName="CMSC 389E Circuitry"
updateJSONURL="https://raw.githubusercontent.com/CMSC-389E/mod-and-testing-framework/master/update.json"
displayURL="https://cs.umd.edu/class/spring2021/cmsc389E"
logoFile="circuitry.png"
authors="Jamie Brassel"
description='''
Adds In and Out Nodes to the game as well as a variety of commands relating to building and testing circuitry.
For UMD class CMSC 389E.
'''